import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;

public class ColorPalette extends JFrame implements ActionListener{
    Color buttonMagenta = new Color(204, 98, 123);
    Color textNavy = new Color(15, 20, 59);
    Color bgOffYellow = new Color(252, 241, 220);
    Color bgPeriwinkle = new Color(212, 208, 242);
    Color textWineRed = new Color(69, 13, 34);
    Color buttonBlue = new Color(64, 147, 214);
    Font pacifico = new Font("Pacifico", Font.PLAIN, 50);
    Font raleway = new Font("Raleway ExtraLight", Font.PLAIN, 20);
    Font ralewayButton = new Font("Raleway ExtraLight", Font.PLAIN, 30);
    JLabel tagText = new JLabel("Choose your Colors!!");
    JLabel titleText = new JLabel("Color Palette");
    EmptyBorder bord = new EmptyBorder(0, 30, 0, 30);
    JButton previous = new JButton("<-");
    JButton next = new JButton("->");
    int i;

    ImageIcon redIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/red.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel redLabel = new JLabel();
    ImageIcon redIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/red.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel redLabel2 = new JLabel();
    ImageIcon redIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/red.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel redLabel3 = new JLabel();
    ImageIcon redIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/red.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel redLabel4 = new JLabel();
    ImageIcon redIcon5 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/red.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel redLabel5 = new JLabel();
    ImageIcon orangeIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel = new JLabel();
    ImageIcon orangeIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel2 = new JLabel();
    ImageIcon orangeIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel3 = new JLabel();
    ImageIcon orangeIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel4 = new JLabel();
    ImageIcon orangeIcon5 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel5 = new JLabel();
    ImageIcon orangeIcon6 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel6 = new JLabel();
    ImageIcon orangeIcon7 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/orange.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel orangeLabel7 = new JLabel();
    ImageIcon purpleIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/purple.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel purpleLabel = new JLabel();
    ImageIcon purpleIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/purple.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel purpleLabel2 = new JLabel();
    ImageIcon purpleIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/purple.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel purpleLabel3 = new JLabel();
    ImageIcon purpleIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/purple.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel purpleLabel4 = new JLabel();
    ImageIcon purpleIcon5 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/purple.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel purpleLabel5 = new JLabel();
    ImageIcon cyanIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/cyan.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel cyanLabel = new JLabel();
    ImageIcon cyanIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/cyan.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel cyanLabel2 = new JLabel();
    ImageIcon cyanIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/cyan.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel cyanLabel3 = new JLabel();
    ImageIcon cyanIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/cyan.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel cyanLabel4 = new JLabel();
    ImageIcon blueIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/blue.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel blueLabel = new JLabel();
    ImageIcon blueIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/blue.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel blueLabel2 = new JLabel();
    ImageIcon blueIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/blue.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel blueLabel3 = new JLabel();
    ImageIcon blueIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/blue.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel blueLabel4 = new JLabel();
    ImageIcon yellowIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel = new JLabel();
    ImageIcon yellowIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel2 = new JLabel();
    ImageIcon yellowIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel3 = new JLabel();
    ImageIcon yellowIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel4 = new JLabel();
    ImageIcon yellowIcon5 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel5 = new JLabel();
    ImageIcon yellowIcon6 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/yellow.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel yellowLabel6 = new JLabel();
    ImageIcon greenIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel = new JLabel();
    ImageIcon greenIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel2 = new JLabel();
    ImageIcon greenIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel3 = new JLabel();
    ImageIcon greenIcon4 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel4 = new JLabel();
    ImageIcon greenIcon5 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel5 = new JLabel();
    ImageIcon greenIcon6 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/green.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel greenLabel6 = new JLabel();
    ImageIcon pinkIcon = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/pink.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel pinkLabel = new JLabel();
    ImageIcon pinkIcon2 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/pink.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel pinkLabel2 = new JLabel();
    ImageIcon pinkIcon3 = new ImageIcon(new ImageIcon("C:/Users/nyuma/programmingII/project/pink.png").getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH));
    JLabel pinkLabel3 = new JLabel();

    JLabel pinkTitle = new JLabel("Pink");
    JLabel redTitle = new JLabel("Red");
    JLabel orangeTitle = new JLabel("Orange");
    JLabel yellowTitle = new JLabel("Yellow");
    JLabel greenTitle = new JLabel("Green");
    JLabel cyanTitle = new JLabel("Cyan");
    JLabel blueTitle = new JLabel("Blue");
    JLabel purpleTitle = new JLabel("Purple");

    JLabel anaPinkLabel = new JLabel("Analogous");
    JLabel compPinkLabel = new JLabel("Complementary");
    JLabel triPinkLabel = new JLabel("Triad");
    JLabel anaRedLabel = new JLabel("Analogous");
    JLabel compRedLabel = new JLabel("Complementary");
    JLabel triRedLabel = new JLabel("Triad");
    JLabel anaOrangeLabel = new JLabel("Analogous");
    JLabel compOrangeLabel = new JLabel("Complementary");
    JLabel triOrangeLabel = new JLabel("Triad");
    JLabel anaYellowLabel = new JLabel("Analogous");
    JLabel compYellowLabel = new JLabel("Complementary");
    JLabel triYellowLabel = new JLabel("Triad");
    JLabel anaBlueLabel = new JLabel("Analogous");
    JLabel compBlueLabel = new JLabel("Complementary");
    JLabel triBlueLabel = new JLabel("Triad");
    JLabel anaCyanLabel = new JLabel("Analogous");
    JLabel compCyanLabel = new JLabel("Complementary");
    JLabel triCyanLabel = new JLabel("Triad");
    JLabel anaPurpleLabel = new JLabel("Analogous");
    JLabel compPurpleLabel = new JLabel("Complementary");
    JLabel triPurpleLabel = new JLabel("Triad");
    JLabel anaGreenLabel = new JLabel("Analogous");
    JLabel compGreenLabel = new JLabel("Complementary");
    JLabel triGreenLabel = new JLabel("Triad");

    JPanel pink = new JPanel();
    JPanel red = new JPanel();
    JPanel orange = new JPanel();
    JPanel yellow = new JPanel();
    JPanel blue = new JPanel();
    JPanel cyan = new JPanel();
    JPanel green = new JPanel();
    JPanel purple = new JPanel();
    JPanel[] panelCarousel = {pink, red, orange, yellow, green, cyan, blue, purple};
    JPanel colors = new JPanel();
    JPanel anaPink = new JPanel();
    JPanel triPink = new JPanel();
    JPanel compPink = new JPanel();
    JPanel anaRed= new JPanel();
    JPanel triRed = new JPanel();
    JPanel compRed = new JPanel();
    JPanel anaOrange = new JPanel();
    JPanel triOrange = new JPanel();
    JPanel compOrange = new JPanel();
    JPanel anaYellow = new JPanel();
    JPanel triYellow = new JPanel();
    JPanel compYellow = new JPanel();
    JPanel anaBlue = new JPanel();
    JPanel triBlue = new JPanel();
    JPanel compBlue = new JPanel();
    JPanel anaGreen = new JPanel();
    JPanel triGreen = new JPanel();
    JPanel compGreen = new JPanel();
    JPanel anaPurple = new JPanel();
    JPanel triPurple = new JPanel();
    JPanel compPurple = new JPanel();
    JPanel anaCyan = new JPanel();
    JPanel triCyan = new JPanel();
    JPanel compCyan = new JPanel();

    public ColorPalette(String name){
        super(name);
        setSize(400,500);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JPanel buttons = new JPanel();
        JPanel titleCenter = new JPanel();

        previous.addActionListener(this);
        next.addActionListener(this);

        buttons.setBackground(bgOffYellow);
        previous.setBackground(buttonBlue);
        previous.setForeground(textWineRed);
        previous.setFont(ralewayButton);
        next.setBackground(buttonBlue);
        next.setForeground(textWineRed);
        next.setFont(ralewayButton);
        titleText.setForeground(buttonBlue);
        titleText.setFont(pacifico);
        tagText.setForeground(textNavy);
        tagText.setFont(raleway);
        tagText.setBackground(bgOffYellow);
        titleCenter.setLayout(new GridLayout(2,1,2,2));
        titleCenter.setBackground(bgOffYellow);
        titleCenter.add(titleText);
        titleCenter.add(tagText);
        buttons.add(previous);
        buttons.add(next);
        colors.setBackground(bgOffYellow);
        pink.setBackground(bgOffYellow);
        anaPink.setBackground(bgOffYellow);
        compPink.setBackground(bgOffYellow);
        triPink.setBackground(bgOffYellow);
        red.setBackground(bgOffYellow);
        anaRed.setBackground(bgOffYellow);
        compRed.setBackground(bgOffYellow);
        triRed.setBackground(bgOffYellow);
        orange.setBackground(bgOffYellow);
        anaOrange.setBackground(bgOffYellow);
        compOrange.setBackground(bgOffYellow);
        triOrange.setBackground(bgOffYellow);
        yellow.setBackground(bgOffYellow);
        anaYellow.setBackground(bgOffYellow);
        compYellow.setBackground(bgOffYellow);
        triYellow.setBackground(bgOffYellow);
        green.setBackground(bgOffYellow);
        anaGreen.setBackground(bgOffYellow);
        compGreen.setBackground(bgOffYellow);
        triGreen.setBackground(bgOffYellow);
        cyan.setBackground(bgOffYellow);
        anaCyan.setBackground(bgOffYellow);
        compCyan.setBackground(bgOffYellow);
        triCyan.setBackground(bgOffYellow);
        blue.setBackground(bgOffYellow);
        anaBlue.setBackground(bgOffYellow);
        compBlue.setBackground(bgOffYellow);
        triBlue.setBackground(bgOffYellow);
        purple.setBackground(bgOffYellow);
        anaPurple.setBackground(bgOffYellow);
        compPurple.setBackground(bgOffYellow);
        triPurple.setBackground(bgOffYellow);

        pinkTitle.setFont(ralewayButton);
        pinkTitle.setForeground(textNavy);
        anaPinkLabel.setFont(raleway);
        anaPinkLabel.setForeground(textNavy);
        compPinkLabel.setFont(raleway);
        compPinkLabel.setForeground(textNavy);
        triPinkLabel.setFont(raleway);
        triPinkLabel.setForeground(textNavy);
        redTitle.setFont(ralewayButton);
        redTitle.setForeground(textNavy);
        anaRedLabel.setFont(raleway);
        anaRedLabel.setForeground(textNavy);
        compRedLabel.setFont(raleway);
        compRedLabel.setForeground(textNavy);
        triRedLabel.setFont(raleway);
        triRedLabel.setForeground(textNavy);
        orangeTitle.setFont(ralewayButton);
        orangeTitle.setForeground(textNavy);
        anaOrangeLabel.setFont(raleway);
        anaOrangeLabel.setForeground(textNavy);
        compOrangeLabel.setFont(raleway);
        compOrangeLabel.setForeground(textNavy);
        triOrangeLabel.setFont(raleway);
        triOrangeLabel.setForeground(textNavy);
        yellowTitle.setFont(ralewayButton);
        yellowTitle.setForeground(textNavy);
        anaYellowLabel.setFont(raleway);
        anaYellowLabel.setForeground(textNavy);
        compYellowLabel.setFont(raleway);
        compYellowLabel.setForeground(textNavy);
        triYellowLabel.setFont(raleway);
        triYellowLabel.setForeground(textNavy);
        greenTitle.setFont(ralewayButton);
        greenTitle.setForeground(textNavy);
        anaGreenLabel.setFont(raleway);
        anaGreenLabel.setForeground(textNavy);
        compGreenLabel.setFont(raleway);
        compGreenLabel.setForeground(textNavy);
        triGreenLabel.setFont(raleway);
        triGreenLabel.setForeground(textNavy);
        cyanTitle.setFont(ralewayButton);
        cyanTitle.setForeground(textNavy);
        anaCyanLabel.setFont(raleway);
        anaCyanLabel.setForeground(textNavy);
        compCyanLabel.setFont(raleway);
        compCyanLabel.setForeground(textNavy);
        triCyanLabel.setFont(raleway);
        triCyanLabel.setForeground(textNavy);
        blueTitle.setFont(ralewayButton);
        blueTitle.setForeground(textNavy);
        anaBlueLabel.setFont(raleway);
        anaBlueLabel.setForeground(textNavy);
        compBlueLabel.setFont(raleway);
        compBlueLabel.setForeground(textNavy);
        triBlueLabel.setFont(raleway);
        triBlueLabel.setForeground(textNavy);
        purpleTitle.setFont(ralewayButton);
        purpleTitle.setForeground(textNavy);
        anaPurpleLabel.setFont(raleway);
        anaPurpleLabel.setForeground(textNavy);
        compPurpleLabel.setFont(raleway);
        compPurpleLabel.setForeground(textNavy);
        triPurpleLabel.setFont(raleway);
        triPurpleLabel.setForeground(textNavy);

        redLabel.setIcon(redIcon);
        redLabel2.setIcon(redIcon2);
        redLabel3.setIcon(redIcon3);
        redLabel4.setIcon(redIcon4);
        redLabel5.setIcon(redIcon5);
        orangeLabel.setIcon(orangeIcon);
        orangeLabel2.setIcon(orangeIcon2);
        orangeLabel3.setIcon(orangeIcon3);
        orangeLabel4.setIcon(orangeIcon4);
        orangeLabel5.setIcon(orangeIcon5);
        orangeLabel6.setIcon(orangeIcon6);
        orangeLabel7.setIcon(orangeIcon7);
        yellowLabel.setIcon(yellowIcon);
        yellowLabel2.setIcon(yellowIcon2);
        yellowLabel3.setIcon(yellowIcon3);
        yellowLabel4.setIcon(yellowIcon4);
        yellowLabel5.setIcon(yellowIcon5);
        yellowLabel6.setIcon(yellowIcon6);
        greenLabel.setIcon(greenIcon);
        greenLabel2.setIcon(greenIcon2);
        greenLabel3.setIcon(greenIcon3);
        greenLabel4.setIcon(greenIcon4);
        greenLabel5.setIcon(greenIcon5);
        greenLabel6.setIcon(greenIcon6);
        cyanLabel.setIcon(cyanIcon);
        cyanLabel2.setIcon(cyanIcon2);
        cyanLabel3.setIcon(cyanIcon3);
        cyanLabel4.setIcon(cyanIcon4);
        blueLabel.setIcon(blueIcon);
        blueLabel2.setIcon(blueIcon2);
        blueLabel3.setIcon(blueIcon3);
        blueLabel4.setIcon(blueIcon4);
        purpleLabel.setIcon(purpleIcon);
        purpleLabel2.setIcon(purpleIcon2);
        purpleLabel3.setIcon(purpleIcon3);
        purpleLabel4.setIcon(purpleIcon4);
        purpleLabel5.setIcon(purpleIcon5);
        pinkLabel.setIcon(pinkIcon);
        pinkLabel2.setIcon(pinkIcon2);
        pinkLabel3.setIcon(pinkIcon3);

        compPink.add(compPinkLabel);
        compPink.add(greenLabel);
        anaPink.add(anaPinkLabel);
        anaPink.add(purpleLabel);
        anaPink.add(redLabel);
        triPink.add(triPinkLabel);
        triPink.add(orangeLabel);
        triPink.add(cyanLabel);
        pink.setLayout(new GridLayout(4, 1, 5, 5));
        pink.add(pinkTitle);
        pink.add(compPink);
        pink.add(anaPink);
        pink.add(triPink);

        compRed.add(compRedLabel);
        compRed.add(greenLabel2);
        anaRed.add(anaRedLabel);
        anaRed.add(pinkLabel);
        anaRed.add(orangeLabel2);
        triRed.add(triRedLabel);
        triRed.add(yellowLabel);
        triRed.add(blueLabel);
        red.setLayout(new GridLayout(4, 1, 5, 5));
        red.add(redTitle);
        red.add(compRed);
        red.add(anaRed);
        red.add(triRed);

        compOrange.add(compOrangeLabel);
        compOrange.add(cyanLabel2);
        anaOrange.add(anaOrangeLabel);
        anaOrange.add(yellowLabel2);
        anaOrange.add(redLabel2);
        triOrange.add(triOrangeLabel);
        triOrange.add(greenLabel3);
        triOrange.add(purpleLabel2);
        orange.setLayout(new GridLayout(4, 1, 5, 5));
        orange.add(orangeTitle);
        orange.add(compOrange);
        orange.add(anaOrange);
        orange.add(triOrange);

        compYellow.add(compYellowLabel);
        compYellow.add(purpleLabel3);
        anaYellow.add(anaYellowLabel);
        anaYellow.add(orangeLabel3);
        anaYellow.add(greenLabel4);
        triYellow.add(triYellowLabel);
        triYellow.add(blueLabel2);
        triYellow.add(redLabel3);
        yellow.setLayout(new GridLayout(4, 1, 5, 5));
        yellow.add(yellowTitle);
        yellow.add(compYellow);
        yellow.add(anaYellow);
        yellow.add(triYellow);

        compGreen.add(compGreenLabel);
        compGreen.add(redLabel4);
        anaGreen.add(anaGreenLabel);
        anaGreen.add(yellowLabel3);
        anaGreen.add(cyanLabel3);
        triGreen.add(triGreenLabel);
        triGreen.add(orangeLabel4);
        triGreen.add(purpleLabel4);
        green.setLayout(new GridLayout(4, 1, 5, 5));
        green.add(greenTitle);
        green.add(compGreen);
        green.add(anaGreen);
        green.add(triGreen);

        compCyan.add(compCyanLabel);
        compCyan.add(orangeLabel5);
        anaCyan.add(anaCyanLabel);
        anaCyan.add(greenLabel5);
        anaCyan.add(blueLabel3);
        triCyan.add(triCyanLabel);
        triCyan.add(pinkLabel2);
        triCyan.add(yellowLabel4);
        cyan.setLayout(new GridLayout(4, 1, 5, 5));
        cyan.add(cyanTitle);
        cyan.add(compCyan);
        cyan.add(anaCyan);
        cyan.add(triCyan);

        compBlue.add(compBlueLabel);
        compBlue.add(orangeLabel6);
        anaBlue.add(anaBlueLabel);
        anaBlue.add(cyanLabel4);
        anaBlue.add(purpleLabel5);
        triBlue.add(triBlueLabel);
        triBlue.add(redLabel5);
        triBlue.add(yellowLabel5);
        blue.setLayout(new GridLayout(4, 1, 5, 5));
        blue.add(blueTitle);
        blue.add(compBlue);
        blue.add(anaBlue);
        blue.add(triBlue);

        compPurple.add(compPurpleLabel);
        compPurple.add(yellowLabel6);
        anaPurple.add(anaPurpleLabel);
        anaPurple.add(blueLabel4);
        anaPurple.add(pinkLabel3);
        triPurple.add(triPurpleLabel);
        triPurple.add(orangeLabel7);
        triPurple.add(greenLabel6);
        purple.setLayout(new GridLayout(4, 1, 5, 5));
        purple.add(purpleTitle);
        purple.add(compPurple);
        purple.add(anaPurple);
        purple.add(triPurple);

        colors.add(pink);
        add(titleCenter, BorderLayout.NORTH);
        add(colors, BorderLayout.CENTER);
        add(buttons, BorderLayout.SOUTH);
    }

    public void actionPerformed(ActionEvent e){
        if(e.getSource() == previous){
            if(i == 0){
                JOptionPane.showMessageDialog(null, "This is the first color.");
            }else{
                i = i-1;
                colors.removeAll();
                colors.add(panelCarousel[i]);
                colors.repaint();
                colors.revalidate();
            }
        }else if(e.getSource() == next){
            if(i == 7){
                JOptionPane.showMessageDialog(null, "This is the last color.");
            }else{
                i = i+1;
                colors.removeAll();
                colors.add(panelCarousel[i]);
                colors.repaint();
                colors.revalidate();
            }

        }else{
            JOptionPane.showMessageDialog(null, "Invalid input.");
        }
    }
    public static void main(String args[]){
        ColorPalette frame = new ColorPalette("Color Palette");
        frame.setVisible(true);
    }
}